services:
  - docker

before-install:
  - docker build -t testdocker .

script:
  - docker run -e CI=true testdocker pip check
  - docker run -e CI=true testdocker safety check
  - docker run -e CI=true testdocker flake8 .
  - docker run -e CI=true testdocker bandit .
